NAME := Monorepo API

.PHONY: dev
dev: ## Starts the service development mode.
	pnpm run dev
	
.PHONY: test
test: ## Execute unit tests.
	pnpm run test

.PHONY: lint
lint: ## Execute lint.
	pnpm run lint
